In [3]:
import pandas as pd

df = pd.read_csv('https://files.zillowstatic.com/research/public_csvs/zhvi/Metro_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv?t=1780781566')
print(df.shape)
print(df.columns.tolist())
df.head()

(895, 321)
['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName', '2000-01-31', '2000-02-29', '2000-03-31', '2000-04-30', '2000-05-31', '2000-06-30', '2000-07-31', '2000-08-31', '2000-09-30', '2000-10-31', '2000-11-30', '2000-12-31', '2001-01-31', '2001-02-28', '2001-03-31', '2001-04-30', '2001-05-31', '2001-06-30', '2001-07-31', '2001-08-31', '2001-09-30', '2001-10-31', '2001-11-30', '2001-12-31', '2002-01-31', '2002-02-28', '2002-03-31', '2002-04-30', '2002-05-31', '2002-06-30', '2002-07-31', '2002-08-31', '2002-09-30', '2002-10-31', '2002-11-30', '2002-12-31', '2003-01-31', '2003-02-28', '2003-03-31', '2003-04-30', '2003-05-31', '2003-06-30', '2003-07-31', '2003-08-31', '2003-09-30', '2003-10-31', '2003-11-30', '2003-12-31', '2004-01-31', '2004-02-29', '2004-03-31', '2004-04-30', '2004-05-31', '2004-06-30', '2004-07-31', '2004-08-31', '2004-09-30', '2004-10-31', '2004-11-30', '2004-12-31', '2005-01-31', '2005-02-28', '2005-03-31', '2005-04-30', '2005-05-31', '2005-06-30', '2005-07-31', '2005-08-31', '2005-09-30', '2005-10-31', '2005-11-30', '2005-12-31', '2006-01-31', '2006-02-28', '2006-03-31', '2006-04-30', '2006-05-31', '2006-06-30', '2006-07-31', '2006-08-31', '2006-09-30', '2006-10-31', '2006-11-30', '2006-12-31', '2007-01-31', '2007-02-28', '2007-03-31', '2007-04-30', '2007-05-31', '2007-06-30', '2007-07-31', '2007-08-31', '2007-09-30', '2007-10-31', '2007-11-30', '2007-12-31', '2008-01-31', '2008-02-29', '2008-03-31', '2008-04-30', '2008-05-31', '2008-06-30', '2008-07-31', '2008-08-31', '2008-09-30', '2008-10-31', '2008-11-30', '2008-12-31', '2009-01-31', '2009-02-28', '2009-03-31', '2009-04-30', '2009-05-31', '2009-06-30', '2009-07-31', '2009-08-31', '2009-09-30', '2009-10-31', '2009-11-30', '2009-12-31', '2010-01-31', '2010-02-28', '2010-03-31', '2010-04-30', '2010-05-31', '2010-06-30', '2010-07-31', '2010-08-31', '2010-09-30', '2010-10-31', '2010-11-30', '2010-12-31', '2011-01-31', '2011-02-28', '2011-03-31', '2011-04-30', '2011-05-31', '2011-06-30', '2011-07-31', '2011-08-31', '2011-09-30', '2011-10-31', '2011-11-30', '2011-12-31', '2012-01-31', '2012-02-29', '2012-03-31', '2012-04-30', '2012-05-31', '2012-06-30', '2012-07-31', '2012-08-31', '2012-09-30', '2012-10-31', '2012-11-30', '2012-12-31', '2013-01-31', '2013-02-28', '2013-03-31', '2013-04-30', '2013-05-31', '2013-06-30', '2013-07-31', '2013-08-31', '2013-09-30', '2013-10-31', '2013-11-30', '2013-12-31', '2014-01-31', '2014-02-28', '2014-03-31', '2014-04-30', '2014-05-31', '2014-06-30', '2014-07-31', '2014-08-31', '2014-09-30', '2014-10-31', '2014-11-30', '2014-12-31', '2015-01-31', '2015-02-28', '2015-03-31', '2015-04-30', '2015-05-31', '2015-06-30', '2015-07-31', '2015-08-31', '2015-09-30', '2015-10-31', '2015-11-30', '2015-12-31', '2016-01-31', '2016-02-29', '2016-03-31', '2016-04-30', '2016-05-31', '2016-06-30', '2016-07-31', '2016-08-31', '2016-09-30', '2016-10-31', '2016-11-30', '2016-12-31', '2017-01-31', '2017-02-28', '2017-03-31', '2017-04-30', '2017-05-31', '2017-06-30', '2017-07-31', '2017-08-31', '2017-09-30', '2017-10-31', '2017-11-30', '2017-12-31', '2018-01-31', '2018-02-28', '2018-03-31', '2018-04-30', '2018-05-31', '2018-06-30', '2018-07-31', '2018-08-31', '2018-09-30', '2018-10-31', '2018-11-30', '2018-12-31', '2019-01-31', '2019-02-28', '2019-03-31', '2019-04-30', '2019-05-31', '2019-06-30', '2019-07-31', '2019-08-31', '2019-09-30', '2019-10-31', '2019-11-30', '2019-12-31', '2020-01-31', '2020-02-29', '2020-03-31', '2020-04-30', '2020-05-31', '2020-06-30', '2020-07-31', '2020-08-31', '2020-09-30', '2020-10-31', '2020-11-30', '2020-12-31', '2021-01-31', '2021-02-28', '2021-03-31', '2021-04-30', '2021-05-31', '2021-06-30', '2021-07-31', '2021-08-31', '2021-09-30', '2021-10-31', '2021-11-30', '2021-12-31', '2022-01-31', '2022-02-28', '2022-03-31', '2022-04-30', '2022-05-31', '2022-06-30', '2022-07-31', '2022-08-31', '2022-09-30', '2022-10-31', '2022-11-30', '2022-12-31', '2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30', '2023-05-31', '2023-06-30', '2023-07-31', '2023-08-31', '2023-09-30', '2023-10-31', '2023-11-30', '2023-12-31', '2024-01-31', '2024-02-29', '2024-03-31', '2024-04-30', '2024-05-31', '2024-06-30', '2024-07-31', '2024-08-31', '2024-09-30', '2024-10-31', '2024-11-30', '2024-12-31', '2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30', '2025-05-31', '2025-06-30', '2025-07-31', '2025-08-31', '2025-09-30', '2025-10-31', '2025-11-30', '2025-12-31', '2026-01-31', '2026-02-28', '2026-03-31', '2026-04-30']

,RegionID,SizeRank,RegionName,RegionType,StateName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,...,2025-07-31,2025-08-31,2025-09-30,2025-10-31,2025-11-30,2025-12-31,2026-01-31,2026-02-28,2026-03-31,2026-04-30
0,102001,0,United States,country,NaN,123427.049538,123644.197286,123913.492467,124491.077769,125155.809204,...,364209.427056,363979.753025,364223.486665,364661.623597,365343.536055,366141.311822,366902.442255,367622.830024,368117.684407,368197.746706
1,394913,1,"New York, NY",msa,NY,217908.609033,218834.597673,219769.162637,221662.952885,223624.038269,...,694306.523004,695095.503604,696494.286361,698826.820996,702164.818651,705580.479548,708640.135014,712208.505439,715991.562187,718396.823077
2,753899,2,"Los Angeles, CA",msa,CA,225552.897453,226392.240410,227510.237225,229734.675324,232167.513239,...,957897.593304,956807.033618,957882.766298,960342.385171,963719.386447,967750.414641,970325.833108,971579.813792,971239.927443,969588.759213
3,394463,3,"Chicago, IL",msa,IL,155258.141365,155401.865176,155675.589704,156356.548308,157175.659600,...,337066.458681,338073.991308,339422.785924,340743.001060,342308.924510,344061.772545,345700.958158,347468.224755,348890.551227,349901.365159
4,394514,4,"Dallas, TX",msa,TX,130734.453703,130792.683285,130859.624151,131033.462549,131262.663716,...,373108.019068,371712.835496,371050.042794,370692.979211,370422.910339,370199.905274,369755.843945,369166.664518,368086.223059,366742.535921

In [4]:
import pandas as pd

df = pd.read_csv('https://files.zillowstatic.com/research/public_csvs/zhvi/Zip_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv?t=1780781566')
print(df.shape)
print(df.columns.tolist())
df.head()

(26276, 325)
['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName', 'State', 'City', 'Metro', 'CountyName', '2000-01-31', '2000-02-29', '2000-03-31', '2000-04-30', '2000-05-31', '2000-06-30', '2000-07-31', '2000-08-31', '2000-09-30', '2000-10-31', '2000-11-30', '2000-12-31', '2001-01-31', '2001-02-28', '2001-03-31', '2001-04-30', '2001-05-31', '2001-06-30', '2001-07-31', '2001-08-31', '2001-09-30', '2001-10-31', '2001-11-30', '2001-12-31', '2002-01-31', '2002-02-28', '2002-03-31', '2002-04-30', '2002-05-31', '2002-06-30', '2002-07-31', '2002-08-31', '2002-09-30', '2002-10-31', '2002-11-30', '2002-12-31', '2003-01-31', '2003-02-28', '2003-03-31', '2003-04-30', '2003-05-31', '2003-06-30', '2003-07-31', '2003-08-31', '2003-09-30', '2003-10-31', '2003-11-30', '2003-12-31', '2004-01-31', '2004-02-29', '2004-03-31', '2004-04-30', '2004-05-31', '2004-06-30', '2004-07-31', '2004-08-31', '2004-09-30', '2004-10-31', '2004-11-30', '2004-12-31', '2005-01-31', '2005-02-28', '2005-03-31', '2005-04-30', '2005-05-31', '2005-06-30', '2005-07-31', '2005-08-31', '2005-09-30', '2005-10-31', '2005-11-30', '2005-12-31', '2006-01-31', '2006-02-28', '2006-03-31', '2006-04-30', '2006-05-31', '2006-06-30', '2006-07-31', '2006-08-31', '2006-09-30', '2006-10-31', '2006-11-30', '2006-12-31', '2007-01-31', '2007-02-28', '2007-03-31', '2007-04-30', '2007-05-31', '2007-06-30', '2007-07-31', '2007-08-31', '2007-09-30', '2007-10-31', '2007-11-30', '2007-12-31', '2008-01-31', '2008-02-29', '2008-03-31', '2008-04-30', '2008-05-31', '2008-06-30', '2008-07-31', '2008-08-31', '2008-09-30', '2008-10-31', '2008-11-30', '2008-12-31', '2009-01-31', '2009-02-28', '2009-03-31', '2009-04-30', '2009-05-31', '2009-06-30', '2009-07-31', '2009-08-31', '2009-09-30', '2009-10-31', '2009-11-30', '2009-12-31', '2010-01-31', '2010-02-28', '2010-03-31', '2010-04-30', '2010-05-31', '2010-06-30', '2010-07-31', '2010-08-31', '2010-09-30', '2010-10-31', '2010-11-30', '2010-12-31', '2011-01-31', '2011-02-28', '2011-03-31', '2011-04-30', '2011-05-31', '2011-06-30', '2011-07-31', '2011-08-31', '2011-09-30', '2011-10-31', '2011-11-30', '2011-12-31', '2012-01-31', '2012-02-29', '2012-03-31', '2012-04-30', '2012-05-31', '2012-06-30', '2012-07-31', '2012-08-31', '2012-09-30', '2012-10-31', '2012-11-30', '2012-12-31', '2013-01-31', '2013-02-28', '2013-03-31', '2013-04-30', '2013-05-31', '2013-06-30', '2013-07-31', '2013-08-31', '2013-09-30', '2013-10-31', '2013-11-30', '2013-12-31', '2014-01-31', '2014-02-28', '2014-03-31', '2014-04-30', '2014-05-31', '2014-06-30', '2014-07-31', '2014-08-31', '2014-09-30', '2014-10-31', '2014-11-30', '2014-12-31', '2015-01-31', '2015-02-28', '2015-03-31', '2015-04-30', '2015-05-31', '2015-06-30', '2015-07-31', '2015-08-31', '2015-09-30', '2015-10-31', '2015-11-30', '2015-12-31', '2016-01-31', '2016-02-29', '2016-03-31', '2016-04-30', '2016-05-31', '2016-06-30', '2016-07-31', '2016-08-31', '2016-09-30', '2016-10-31', '2016-11-30', '2016-12-31', '2017-01-31', '2017-02-28', '2017-03-31', '2017-04-30', '2017-05-31', '2017-06-30', '2017-07-31', '2017-08-31', '2017-09-30', '2017-10-31', '2017-11-30', '2017-12-31', '2018-01-31', '2018-02-28', '2018-03-31', '2018-04-30', '2018-05-31', '2018-06-30', '2018-07-31', '2018-08-31', '2018-09-30', '2018-10-31', '2018-11-30', '2018-12-31', '2019-01-31', '2019-02-28', '2019-03-31', '2019-04-30', '2019-05-31', '2019-06-30', '2019-07-31', '2019-08-31', '2019-09-30', '2019-10-31', '2019-11-30', '2019-12-31', '2020-01-31', '2020-02-29', '2020-03-31', '2020-04-30', '2020-05-31', '2020-06-30', '2020-07-31', '2020-08-31', '2020-09-30', '2020-10-31', '2020-11-30', '2020-12-31', '2021-01-31', '2021-02-28', '2021-03-31', '2021-04-30', '2021-05-31', '2021-06-30', '2021-07-31', '2021-08-31', '2021-09-30', '2021-10-31', '2021-11-30', '2021-12-31', '2022-01-31', '2022-02-28', '2022-03-31', '2022-04-30', '2022-05-31', '2022-06-30', '2022-07-31', '2022-08-31', '2022-09-30', '2022-10-31', '2022-11-30', '2022-12-31', '2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30', '2023-05-31', '2023-06-30', '2023-07-31', '2023-08-31', '2023-09-30', '2023-10-31', '2023-11-30', '2023-12-31', '2024-01-31', '2024-02-29', '2024-03-31', '2024-04-30', '2024-05-31', '2024-06-30', '2024-07-31', '2024-08-31', '2024-09-30', '2024-10-31', '2024-11-30', '2024-12-31', '2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30', '2025-05-31', '2025-06-30', '2025-07-31', '2025-08-31', '2025-09-30', '2025-10-31', '2025-11-30', '2025-12-31', '2026-01-31', '2026-02-28', '2026-03-31', '2026-04-30']

,RegionID,SizeRank,RegionName,RegionType,StateName,State,City,Metro,CountyName,2000-01-31,...,2025-07-31,2025-08-31,2025-09-30,2025-10-31,2025-11-30,2025-12-31,2026-01-31,2026-02-28,2026-03-31,2026-04-30
0,91982,1,77494,zip,TX,TX,Katy,"Houston-The Woodlands-Sugar Land, TX",Fort Bend County,211041.005329,...,493611.981869,492490.195382,492692.837484,493445.443112,494524.551492,495131.184301,494732.516894,493303.297817,491671.876271,489900.281466
1,61148,2,8701,zip,NJ,NJ,Lakewood,"New York-Newark-Jersey City, NY-NJ-PA",Ocean County,113107.940019,...,543090.959009,544341.283601,546905.912540,551821.486041,557770.333985,564044.483445,568535.788174,572276.269997,575223.660538,577895.151126
2,91940,3,77449,zip,TX,TX,Katy,"Houston-The Woodlands-Sugar Land, TX",Harris County,104955.931168,...,277240.630382,276294.644916,275506.866356,274758.533310,274115.630288,273772.685442,273217.060982,272811.268664,272413.963259,272122.210142
3,62080,4,11368,zip,NY,NY,New York,"New York-Newark-Jersey City, NY-NJ-PA",Queens County,168141.944305,...,518740.000548,520355.644223,521555.324508,522550.762047,524410.419569,527020.920312,531651.968961,536447.865586,541178.231366,543161.437084
4,91733,5,77084,zip,TX,TX,Houston,"Houston-The Woodlands-Sugar Land, TX",Harris County,104704.775938,...,273656.086467,272762.684406,271867.517224,271000.272267,270256.217132,269906.006551,269391.827130,268904.230398,268418.343637,267990.471321

In [5]:
print(f"Total zip codes: {df.shape[0]}")
print(f"Date columns: {df.shape[1] - 9}")
print(f"\nNull values per key column:")
print(df[['RegionName','State','City','Metro','CountyName']].isnull().sum())
print(f"\nSample of states covered:")
print(df['State'].value_counts().head(10))

Total zip codes: 26276
Date columns: 316

Null values per key column:
RegionName       0
State            0
City          1039
Metro         4715
CountyName       0
dtype: int64

Sample of states covered:
State
NY    1561
CA    1543
TX    1513
PA    1362
IL    1084
OH    1024
FL     924
MI     892
IA     824
MO     759
Name: count, dtype: int64

In [6]:
il_df = df[df['State'] == 'IL']
print(f"Illinois zip codes: {len(il_df)}")
print(f"Missing metro in IL: {il_df['Metro'].isnull().sum()}")
print(f"\nTop IL cities by zip count:")
print(il_df['City'].value_counts().head(10))

Illinois zip codes: 1084
Missing metro in IL: 166

Top IL cities by zip count:
City
Chicago             56
Rockford             8
Peoria               7
Aurora               5
Springfield          5
Joliet               4
Bloomington          4
Schaumburg           4
East Saint Louis     4
Naperville           4
Name: count, dtype: int64

In [7]:
top_metros = df[df['Metro'].notna()]['Metro'].value_counts().head(10)
print(top_metros)

Metro
New York-Newark-Jersey City, NY-NJ-PA           831
Chicago-Naperville-Elgin, IL-IN-WI              380
Los Angeles-Long Beach-Anaheim, CA              360
Philadelphia-Camden-Wilmington, PA-NJ-DE-MD     334
Washington-Arlington-Alexandria, DC-VA-MD-WV    320
Pittsburgh, PA                                  295
Boston-Cambridge-Newton, MA-NH                  272
Dallas-Fort Worth-Arlington, TX                 255
Minneapolis-St. Paul-Bloomington, MN-WI         225
St. Louis, MO-IL                                223
Name: count, dtype: int64

In [8]:
top_metro_names = top_metros.index.tolist()
metro_df = df[df['Metro'].isin(top_metro_names)].copy()

print(f"Total zip codes in top 10 metros: {len(metro_df)}")
print(f"\nNull values in date columns (sample):")
date_cols = [col for col in metro_df.columns if col.startswith('20')]
print(metro_df[date_cols].isnull().sum().describe())

Total zip codes in top 10 metros: 3495

Null values in date columns (sample):
count    316.000000
mean     243.224684
std      201.829781
min        0.000000
25%       57.000000
50%      152.000000
75%      424.250000
max      636.000000
dtype: float64

In [9]:
null_by_date = metro_df[date_cols].isnull().sum()
print("First 10 date columns (nulls):")
print(null_by_date.head(10))
print("\nLast 10 date columns (nulls):")
print(null_by_date.tail(10))

First 10 date columns (nulls):
2000-01-31    636
2000-02-29    628
2000-03-31    623
2000-04-30    621
2000-05-31    620
2000-06-30    620
2000-07-31    620
2000-08-31    620
2000-09-30    620
2000-10-31    618
dtype: int64

Last 10 date columns (nulls):
2025-07-31    0
2025-08-31    0
2025-09-30    0
2025-10-31    0
2025-11-30    0
2025-12-31    0
2026-01-31    0
2026-02-28    1
2026-03-31    1
2026-04-30    1
dtype: int64

In [10]:
null_threshold = 50
clean_dates = null_by_date[null_by_date <= null_threshold].index.tolist()
print(f"First clean date: {clean_dates[0]}")
print(f"Total clean date columns: {len(clean_dates)}")

First clean date: 2021-02-28
Total clean date columns: 63

In [11]:
working_df = metro_df[['RegionID', 'RegionName', 'State', 'City', 'Metro', 'CountyName'] + clean_dates].copy()
print(f"Shape: {working_df.shape}")
print(f"Date range: {clean_dates[0]} to {clean_dates[-1]}")
print(f"Zip codes: {len(working_df)}")
working_df.head()

Shape: (3495, 69)
Date range: 2021-02-28 to 2026-04-30
Zip codes: 3495

,RegionID,RegionName,State,City,Metro,CountyName,2021-02-28,2021-03-31,2021-04-30,2021-05-31,...,2025-07-31,2025-08-31,2025-09-30,2025-10-31,2025-11-30,2025-12-31,2026-01-31,2026-02-28,2026-03-31,2026-04-30
1,61148,8701,NJ,Lakewood,"New York-Newark-Jersey City, NY-NJ-PA",Ocean County,304572.854764,308068.551595,312670.302665,318388.862248,...,543090.959009,544341.283601,546905.912540,551821.486041,557770.333985,564044.483445,568535.788174,572276.269997,575223.660538,577895.151126
3,62080,11368,NY,New York,"New York-Newark-Jersey City, NY-NJ-PA",Queens County,578171.123709,580453.615214,579766.167655,579459.808791,...,518740.000548,520355.644223,521555.324508,522550.762047,524410.419569,527020.920312,531651.968961,536447.865586,541178.231366,543161.437084
6,62093,11385,NY,New York,"New York-Newark-Jersey City, NY-NJ-PA",Queens County,761324.522990,763886.111913,768027.769074,772491.384336,...,839593.862898,840669.465432,842930.635993,846249.201140,848865.695495,850643.725274,852437.650416,856988.519642,861952.220426,864208.959016
8,62019,11208,NY,New York,"New York-Newark-Jersey City, NY-NJ-PA",Kings County,606153.291119,609826.384619,614798.197269,619543.555109,...,697699.441509,698957.511490,700954.964879,703509.274254,707537.169706,711970.778274,717411.978999,723620.722874,728627.522460,729721.339355
9,95992,90011,CA,Los Angeles,"Los Angeles-Long Beach-Anaheim, CA",Los Angeles County,506262.495413,507639.286532,511916.836203,516983.390680,...,593237.644978,596608.672127,601411.655767,604610.264126,606540.675072,609058.963611,609958.068762,609332.658404,606109.682285,602357.175499

In [13]:
working_df.to_csv('../data/Processed/metro_clean.csv', index=False)
print("Saved!")

Saved!